changelog:
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 📝 Documentation
      labels:
        - documentation
    - title: ⚡ Performance Improvements
      labels:
        - performance
    - title: 🔨 Maintenance
      labels:
        - maintenance
        - refactor
    - title: 🧪 Tests
      labels:
        - test
    - title: 📦 Dependencies
      labels:
        - dependencies