runtime: python39
env: standard
instance_class: F1

handlers:
  - url: /(.*)
    static_files: build/web/\1
    upload: build/web/(.*)
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}

inbound_services:
- warmup