name: eco_tracker
description: An eco-friendly tracking application built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2
  
  # Firebase dependencies
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.9.1
  
  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Routing
  go_router: ^10.1.2
  
  # HTTP client
  dio: ^5.3.2
  
  # UI utilities
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  mockito: ^5.4.2
  flutter_lints: ^2.0.3
  test: ^1.24.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  # Add assets here when needed
  # assets:
  #   - assets/images/
  
  # Add fonts here when needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
